url = "http://remoquete.com"
baseurl = "/"
title = "Remoquete.com"
theme = "hermit"
pygmentsCodefences  = true
pygmentsUseClasses  = true
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.
enableEmoji = true  # Shorthand emojis in content files - https://gohugo.io/functions/emojify/
publishDir = "docs"

[author]
  name = "Fabrizio Ferri-Benedetti"
  
[taxonomies]
  tag = "tags"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02" 
  dateformNumTime = "2006-01-02T15:04:00+00:00"

  themeColor = "#494f5c"

  homeSubtitle = "Soy psicólogo, pero en mi diván quien se tumba es la tecnología. A veces dice cosas interesantes."
  footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
  justifyContent = false  # Set "text-align: justify" to `.content`.

[menu]

  [[menu.main]]
    name = "Todos los posts"
    url = "posts/"
    weight = 10
  [[menu.main]]
    name = "Passo.uno"
    url = "https://passo.uno"
    weight = 11